//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.16 at 07:54:15 AM CEST 
//


package hr.algebra.iis_soap.dto.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="groot"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="geonameid" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="capital" type="{http://www.algebra.hr/iis_soap/dto/xml}Capital"/&gt;
 *         &lt;element name="area_size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="population" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="phone_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="is_in_eu" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="languages" type="{http://www.algebra.hr/iis_soap/dto/xml}languages"/&gt;
 *         &lt;element name="flag" type="{http://www.algebra.hr/iis_soap/dto/xml}Flag"/&gt;
 *         &lt;element name="tld" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="depends_on" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="territories" type="{http://www.algebra.hr/iis_soap/dto/xml}territories"/&gt;
 *         &lt;element name="wiki_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="wiki_url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="total_iso_divisions" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="total_adm_divisions" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="total_cities" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="currency" type="{http://www.algebra.hr/iis_soap/dto/xml}Currency"/&gt;
 *         &lt;element name="timezone" type="{http://www.algebra.hr/iis_soap/dto/xml}Timezone"/&gt;
 *         &lt;element name="continent" type="{http://www.algebra.hr/iis_soap/dto/xml}Continent"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groot", propOrder = {
    "geonameid",
    "name",
    "code",
    "capital",
    "areaSize",
    "population",
    "phoneCode",
    "isInEu",
    "languages",
    "flag",
    "tld",
    "dependsOn",
    "territories",
    "wikiId",
    "wikiUrl",
    "totalIsoDivisions",
    "totalAdmDivisions",
    "totalCities",
    "currency",
    "timezone",
    "continent",
    "status"
})
public class Groot {

    protected int geonameid;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String code;
    @XmlElement(required = true)
    protected Capital capital;
    @XmlElement(name = "area_size", required = true)
    protected String areaSize;
    protected int population;
    @XmlElement(name = "phone_code", required = true)
    protected String phoneCode;
    @XmlElement(name = "is_in_eu")
    protected boolean isInEu;
    @XmlElement(required = true)
    protected Languages languages;
    @XmlElement(required = true)
    protected Flag flag;
    @XmlElement(required = true)
    protected String tld;
    @XmlElement(name = "depends_on", required = true)
    protected Object dependsOn;
    @XmlElement(required = true)
    protected Territories territories;
    @XmlElement(name = "wiki_id", required = true)
    protected String wikiId;
    @XmlElement(name = "wiki_url", required = true)
    protected String wikiUrl;
    @XmlElement(name = "total_iso_divisions")
    protected int totalIsoDivisions;
    @XmlElement(name = "total_adm_divisions")
    protected int totalAdmDivisions;
    @XmlElement(name = "total_cities")
    protected int totalCities;
    @XmlElement(required = true)
    protected Currency currency;
    @XmlElement(required = true)
    protected Timezone timezone;
    @XmlElement(required = true)
    protected Continent continent;
    @XmlElement(required = true)
    protected String status;

    /**
     * Gets the value of the geonameid property.
     * 
     */
    public int getGeonameid() {
        return geonameid;
    }

    /**
     * Sets the value of the geonameid property.
     * 
     */
    public void setGeonameid(int value) {
        this.geonameid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the capital property.
     * 
     * @return
     *     possible object is
     *     {@link Capital }
     *     
     */
    public Capital getCapital() {
        return capital;
    }

    /**
     * Sets the value of the capital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capital }
     *     
     */
    public void setCapital(Capital value) {
        this.capital = value;
    }

    /**
     * Gets the value of the areaSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaSize() {
        return areaSize;
    }

    /**
     * Sets the value of the areaSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaSize(String value) {
        this.areaSize = value;
    }

    /**
     * Gets the value of the population property.
     * 
     */
    public int getPopulation() {
        return population;
    }

    /**
     * Sets the value of the population property.
     * 
     */
    public void setPopulation(int value) {
        this.population = value;
    }

    /**
     * Gets the value of the phoneCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneCode() {
        return phoneCode;
    }

    /**
     * Sets the value of the phoneCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneCode(String value) {
        this.phoneCode = value;
    }

    /**
     * Gets the value of the isInEu property.
     * 
     */
    public boolean isIsInEu() {
        return isInEu;
    }

    /**
     * Sets the value of the isInEu property.
     * 
     */
    public void setIsInEu(boolean value) {
        this.isInEu = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languages }
     *     
     */
    public Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languages }
     *     
     */
    public void setLanguages(Languages value) {
        this.languages = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     * @return
     *     possible object is
     *     {@link Flag }
     *     
     */
    public Flag getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flag }
     *     
     */
    public void setFlag(Flag value) {
        this.flag = value;
    }

    /**
     * Gets the value of the tld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTld() {
        return tld;
    }

    /**
     * Sets the value of the tld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTld(String value) {
        this.tld = value;
    }

    /**
     * Gets the value of the dependsOn property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDependsOn() {
        return dependsOn;
    }

    /**
     * Sets the value of the dependsOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDependsOn(Object value) {
        this.dependsOn = value;
    }

    /**
     * Gets the value of the territories property.
     * 
     * @return
     *     possible object is
     *     {@link Territories }
     *     
     */
    public Territories getTerritories() {
        return territories;
    }

    /**
     * Sets the value of the territories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Territories }
     *     
     */
    public void setTerritories(Territories value) {
        this.territories = value;
    }

    /**
     * Gets the value of the wikiId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWikiId() {
        return wikiId;
    }

    /**
     * Sets the value of the wikiId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWikiId(String value) {
        this.wikiId = value;
    }

    /**
     * Gets the value of the wikiUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWikiUrl() {
        return wikiUrl;
    }

    /**
     * Sets the value of the wikiUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWikiUrl(String value) {
        this.wikiUrl = value;
    }

    /**
     * Gets the value of the totalIsoDivisions property.
     * 
     */
    public int getTotalIsoDivisions() {
        return totalIsoDivisions;
    }

    /**
     * Sets the value of the totalIsoDivisions property.
     * 
     */
    public void setTotalIsoDivisions(int value) {
        this.totalIsoDivisions = value;
    }

    /**
     * Gets the value of the totalAdmDivisions property.
     * 
     */
    public int getTotalAdmDivisions() {
        return totalAdmDivisions;
    }

    /**
     * Sets the value of the totalAdmDivisions property.
     * 
     */
    public void setTotalAdmDivisions(int value) {
        this.totalAdmDivisions = value;
    }

    /**
     * Gets the value of the totalCities property.
     * 
     */
    public int getTotalCities() {
        return totalCities;
    }

    /**
     * Sets the value of the totalCities property.
     * 
     */
    public void setTotalCities(int value) {
        this.totalCities = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link Timezone }
     *     
     */
    public Timezone getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timezone }
     *     
     */
    public void setTimezone(Timezone value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the continent property.
     * 
     * @return
     *     possible object is
     *     {@link Continent }
     *     
     */
    public Continent getContinent() {
        return continent;
    }

    /**
     * Sets the value of the continent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Continent }
     *     
     */
    public void setContinent(Continent value) {
        this.continent = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
