//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.03 at 01:08:15 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.algebra.hr/iis_soap/dto/xml", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.algebra.iis_soap.dto.xml;
