//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.16 at 07:54:15 AM CEST 
//


package hr.algebra.iis_soap.dto.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Timezone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Timezone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gtm_offset" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="gmt_offset" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="is_daylight_saving" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Timezone", propOrder = {
    "timezone",
    "gtmOffset",
    "gmtOffset",
    "isDaylightSaving",
    "code"
})
public class Timezone {

    @XmlElement(required = true)
    protected String timezone;
    @XmlElement(name = "gtm_offset")
    protected int gtmOffset;
    @XmlElement(name = "gmt_offset")
    protected int gmtOffset;
    @XmlElement(name = "is_daylight_saving")
    protected boolean isDaylightSaving;
    @XmlElement(required = true)
    protected String code;

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the gtmOffset property.
     * 
     */
    public int getGtmOffset() {
        return gtmOffset;
    }

    /**
     * Sets the value of the gtmOffset property.
     * 
     */
    public void setGtmOffset(int value) {
        this.gtmOffset = value;
    }

    /**
     * Gets the value of the gmtOffset property.
     * 
     */
    public int getGmtOffset() {
        return gmtOffset;
    }

    /**
     * Sets the value of the gmtOffset property.
     * 
     */
    public void setGmtOffset(int value) {
        this.gmtOffset = value;
    }

    /**
     * Gets the value of the isDaylightSaving property.
     * 
     */
    public boolean isIsDaylightSaving() {
        return isDaylightSaving;
    }

    /**
     * Sets the value of the isDaylightSaving property.
     * 
     */
    public void setIsDaylightSaving(boolean value) {
        this.isDaylightSaving = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
